### ISSUE TITLE
Проблема с перезаписью элементов

### ISSUE THREAD

**Issue by NorthDev10** [GyverLibs/GyverFIFO#1]
Если это просто FIFO, то тут все логично, но если это кольцевой буффер (ring-buffer), то мне кажется тут есть проблемка:
при заполненни буфера - запись останавливается, а по идее должна перезаписоватся.

Еще заметил, что при создании буфера из 5 элементов и записи 7 элементов - сохранилось только 4

**Comment by GyverLibs** [comment]
> Если это просто FIFO, то тут все логично

Название библиотеки намекает)

Для проверки свободного места есть available for write. Если нужен циклический буфер с перезаписью - библа GyverLBUF
